spring.application.name=catalog-service
server.port=8081

###### Database #####
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/myshop_catalog?useSSL=false
spring.datasource.username=dev
spring.datasource.password=dev

logging.level.com.myshop=INFO



